# Welcome to Jekyll!
#

# Site settings
title: Bas Paap
description: |
  the things I've done  
  and things I can do  
  for you
owner: Bas Paap # or company name
first_published: 2018 #if migrating another site, the year of your first publish
email: baspaap@live.nl
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://baspaap.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/baspaap
  #github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/baspaap
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:baspaap@live.nl
  #flickr:
  instagram: https://www.instagram.com/hooks_for_feet/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
